### ISSUE TITLE
Is there any documentation about how to use this?

### ISSUE THREAD

**Issue by BrianGilbert** [mAKEkr/vuepress-plugin-blog-advance#2]
Very new to Vuepress, and looking to use this plugin, but not really sure about how to use it properly.

@mAKEkr would if be possible for a little more detail on how and where to create content files for this please?

I'm hoping to have the blog part of my site at /blog/, and latest posts below intro page on site

**Comment by mAKEkr** [comment]
this plugin based on `vuepress default blog plugin`. you can available check in https://github.com/vuejs/vuepress/tree/master/packages/%40vuepress/plugin-blog
default blog plugin and my plugin both using `_posts` directory.
basic usages of this plugin, write any markdown on _posts directory, blog plugin compiled into posts.
if want full example, I recommend check into eogist's repository https://github.com/ulivz/vuepress-blog-example-egoist

**Comment by BrianGilbert** [comment]
Thanks @mAKEkr thosew links should get me started.
